ecomm_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("payment.urls")),

]

payment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:order_id>/', views.payment_page, name='payment_page'),
]

payment/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Order #{self.id}"

class PaymentDetail(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    payment_method = models.CharField(max_length=20)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"Payment for {self.order}"

payment/forms.py
from django import forms

class PaymentForm(forms.Form):
    payment_method = forms.ChoiceField(choices=[('paypal', 'PayPal'), ('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery')], widget=forms.RadioSelect)

payment/views.py
from django.shortcuts import render, get_object_or_404
from .models import Order, PaymentDetail
from .forms import PaymentForm

# Create your views here.

def payment_page(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    form = PaymentForm()

    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            payment_method = form.cleaned_data['payment_method']
            payment_detail = PaymentDetail(order=order, payment_method=payment_method)
            payment_detail.save()
            order.payment = payment_detail
            order.save()

            return render(request, 'payment/success.html', {'order': order, 'payment_detail': payment_detail})

    return render(request, 'payment/payment.html', {'order': order, 'form': form})

payment/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
    <title>E-commerce Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

payment/templates/payment.html
{% extends 'base.html' %}

{% block content %}
<h1>Order Summary</h1>
<p>Product: {{ order.product.name }}</p>
<p>Quantity: {{ order.quantity }}</p>
<p>Total Amount: ${{ order.total_amount }}</p>

<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Proceed to Payment</button>
</form>
{% endblock %}

payment/templates/success.html
{% extends 'base.html' %}

{% block content %}
<h1>Payment Successful</h1>
<p>Order ID: {{ order.id }}</p>
<p>Total Amount: ${{ order.total_amount }}</p>
<p>Payment Method: {{ payment_detail.get_payment_method_display }}</p>
{% endblock %}